admin:
    modules:
            system:
                - 
                    name      : System / Localization
                    callback  : Admin/systemAdmin/localization
                    self-test : Admin/noop
                    visibility: admin
                - 
                    name      : Foo / Bar
                    callback  : Admin/systemAdmin/localization
                    self-test : Admin/noop
                    visibility: admin
        