admin:
    modules:
            system:
                - 
                    name      : System / Localization
                    callback  : Admin/systemAdmin/localization
                    self-test : Admin/testLocalization
                    visibility: admin
                -
                    name      : System / Database
                    callback  : Admin/systemAdmin/database
                    self-test : Admin/testDatabase
                    visibility: admin
                -
                    name      : System / .htaccess
                    callback  : Admin/systemAdmin/htaccess
                    self-test : 
                    visibility: admin
