admin:
  modules:
    system:
      - 
        # Currently I'm providing all values to serve as a source of documentation for possible values
        name      : System / Localization
        callback  : Admin/system/localization
        self-test : Admin/noop
        visibility: admin
        