admin:
    modules:
            system:
                - 
                    name      : System / Localization
                    callback  : Admin/systemAdmin/localization
                    self-test : Admin/testLocalization
                    visibility: admin
            database:
                -
                    name      : Database / Connectivity
                    callback  : Admin/databaseAdmin/connectivity
                    self-test : Admin/testConnectivity
                    visibility: admin
